export enum apiRoutes {
  LOGIN = '/login',
  SIGNUP = '/signup',
  SIGNOUT = '/auth/signout',
  FETCH_ME = '/users/me',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_USER = '/auth',
  FETCH_USERS = '/users',
  USERS_PREFIX = '/users',
  UPLOAD_AVATAR_IMAGE = '/users/upload',
  FETCH_ALLAUCTIONS = '/auctions',
  FETCH_MYAUCTIONS = '/auctions/my-auctions',
  FETCH_BIDDING = '/auctions/bidding',
  FETCH_WON = 'auctions/won',
  GET_AVATAR_IMAGE = '/users/get/image',
  PRODUCTS_PREFIX = '/products',
  ROLES_PREFIX = '/roles',
  ORDERS_PREFIX = '/orders',
  PERMISSIONS_PREFIX = '/permissions',
}
